// 自動生成：あなたのSupabase接続情報（公開OKな anon キー）
export const SUPABASE_URL = "https://yuazfkhebghlbotfvmze.supabase.co";
export const SUPABASE_ANON_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6Inl1YXpma2hlYmdobGJvdGZ2bXplIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NTQ4MTM2NDQsImV4cCI6MjA3MDM4OTY0NH0.pEJkkbT6pPW__Sv0Zjhe2igCk5YtkT6c1HU9_wogDcE";
